// Name: Generate Article

import "@johnlindquist/kit"
import { editorChain } from "../lib/chain"

let input = await arg("Enter a topic for your article")

let title = await editorChain(
  `Generate 3 titles for an article based on the following topic.
Start each title on a new line with a "*" and a space.`,
  input
)

let header = await editorChain(
  `Generate 3 section headers for an article based on the following title.
Start each header on a new line with a "*" and a space.`,
  title
)

let content = await editorChain(
  `Generate 3 short variations of an opening paragraph of content for an article titled "${title}" inside of the following section.
Start each paragraph on a new line with a "*" and a space.`,
  header
)

let contents = await editor(`# ${title}

## ${header}

${content}
`)

let final = await editorChain(
  `
The article below was generated by you.
I'm adding //AI: comments where I want you to fix and improve the article.
Fix the //AI: comments and leave //CHANGED: comments in there place so I can see what changed
`,
  contents
)

let filePath = tmpPath("article.md")
await writeFile(filePath, final)
await edit(filePath)
