// Users/johnlindquist/.kenv/kenvs/ai-generate/scripts/generate-article.ts
import "@johnlindquist/kit";

// Users/johnlindquist/.kenv/kenvs/ai-generate/lib/chain.ts
var createChain = async (promptTemplate, handlers) => {
  let { ChatOpenAI } = await import("langchain/chat_models");
  let { ConversationChain } = await import("langchain/chains");
  let { CallbackManager } = await import("langchain/callbacks");
  let { BufferMemory } = await import("langchain/memory");
  let { MessagesPlaceholder } = await import("langchain/prompts");
  let { ChatPromptTemplate, HumanMessagePromptTemplate, SystemMessagePromptTemplate } = await import("langchain/prompts");
  let prompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(promptTemplate.trim()),
    new MessagesPlaceholder("history"),
    HumanMessagePromptTemplate.fromTemplate("{input}")
  ]);
  let openAIApiKey = await env("OPENAI_API_KEY", {
    hint: `Grab a key from <a href="https://platform.openai.com/account/api-keys">here</a>`
  });
  let llm = new ChatOpenAI({
    modelName: "gpt-4",
    openAIApiKey,
    streaming: true,
    callbackManager: CallbackManager.fromHandlers(handlers)
  });
  let memory = new BufferMemory({
    returnMessages: true
  });
  let chain = new ConversationChain({
    llm,
    prompt,
    memory
  });
  return chain;
};
var editorId = 0;
var savePath = ``;
var editorChain = async (prompt, input2) => {
  let commands = [];
  let currentEditorId = editorId;
  if (!savePath) {
    let { default: slugify } = await import("slugify");
    let name = slugify(input2.slice(0, 20), { lower: true, trim: true });
    savePath = tmpPath(`${name}.txt`);
  }
  let createShortcut = (num) => {
    return {
      key: `${cmd}+${num}`,
      name: `Select ${num}`,
      bar: "right",
      onPress: async (input3) => {
        let selected = input3.split(`*`).map((text) => text.trim()).filter(Boolean)[num - 1];
        submit(selected);
      }
    };
  };
  let createRegenShortcut = (chain2) => {
    return {
      key: `${cmd}+4`,
      name: "Regenerate",
      bar: "right",
      onPress: async (input3) => {
        setInput("");
        chain2.call({
          input: "Generate 3 more. Start each with a * and a space."
        });
      }
    };
  };
  let shortcuts = [createShortcut(1), createShortcut(2), createShortcut(3)];
  let id = null;
  let chain = await createChain(prompt, {
    handleLLMStart: async (llm, prompts) => {
      log(prompts.join("\n"));
      setInterval(async () => {
        if (commands.length) {
          let command = commands.shift();
          command();
        }
      }, 100);
    },
    handleLLMNewToken: async (token) => {
      if (!token)
        return;
      if (currentEditorId !== editorId)
        return;
      commands.push(async () => {
        await editor.append(token);
        await appendFile(savePath, token);
      });
    },
    handleLLMEnd: async (output, verbose) => {
      clearInterval(id);
      await Promise.all(commands);
    }
  });
  let result = await editor({
    onInit: async () => {
      await chain.call({
        input: input2
      });
    },
    shortcuts: [...shortcuts, createRegenShortcut(chain)]
  });
  editorId++;
  return result;
};

// Users/johnlindquist/.kenv/kenvs/ai-generate/scripts/generate-article.ts
var input = await arg("Enter a topic for your article");
var title = await editorChain(
  `Generate 3 titles for an article based on the following topic.
Start each title on a new line with a "*" and a space.`,
  input
);
var header = await editorChain(
  `Generate 3 section headers for an article based on the following title.
Start each header on a new line with a "*" and a space.`,
  title
);
var content = await editorChain(
  `Generate 3 short variations of an opening paragraph of content for an article titled "${title}" inside of the following section.
Start each paragraph on a new line with a "*" and a space.`,
  header
);
var contents = await editor(`# ${title}

## ${header}

${content}
`);
var final = await editorChain(
  `
The article below was generated by you.
I'm adding //AI: comments where I want you to fix and improve the article.
Fix the //AI: comments and leave //CHANGED: comments in there place so I can see what changed
`,
  contents
);
var filePath = tmpPath("article.md");
await writeFile(filePath, final);
await edit(filePath);
